[package]
name = "rust-htmx-prod"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.5"
actix-web = "3"
serde = "1"

# CHANGE LATER
handlebars = { version = "3", features = ["dir_source"] }